CREATE TABLE public.perfiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username VARCHAR UNIQUE NOT NULL,
    nombre VARCHAR NOT NULL,
    apellido VARCHAR NOT NULL,
    segundo_apellido VARCHAR,
    rol_app VARCHAR NOT NULL CHECK (rol_app IN ('admin', 'voluntario')),
    rol_sistema VARCHAR CHECK (rol_sistema IN ('administracion', 'coordinacion', 'direccion', 'gestion_voluntariado')),
    activo BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK ((rol_app = 'voluntario' AND rol_sistema IS NULL)
            OR
            (rol_app = 'admin' AND rol_sistema IS NOT NULL))
);

CREATE TABLE public.centros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR UNIQUE NOT NULL,
    img VARCHAR,
    estado VARCHAR NOT NULL CHECK (estado IN ('activo', 'inactivo')),
    responsable_id UUID REFERENCES public.perfiles(id) ON DELETE SET NULL,
    mapa_url VARCHAR,
    descripcion TEXT
);

CREATE TABLE public.vols (
    id UUID PRIMARY KEY REFERENCES public.perfiles(id) DELETE ON CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_nacimiento DATE NOT NULL,
    -- i think this can actually be null bc someone can have a phone but not an email and vice versa, but one needs to be required
    telefono VARCHAR,
    correo VARCHAR UNIQUE,
    area VARCHAR NOT NULL CHECK (area IN ('educacion', 'comunicacion')),
    rol VARCHAR NOT NULL CHECK (rol IN ('apoyo', 'lider', 'responsable'))
    tipo_voluntario VARCHAR NOT NULL CHECK (tipo_voluntario IN ('nacional', 'internacional')),
    pais_origen VARCHAR NOT NULL,
    area_estudio TEXT,
    activo BOOLEAN NOT NULL,
    horas_semana INT NOT NULL CHECK (horas_semana >= 0 AND horas_semana <= 40),
    faltas INT CHECK (faltas >=0 AND faltas <= 3)
    centro_preferido_id INT REFERENCES public.centros(id),
    comentarios TEXT,

    CHECK ((telefono IS NULL AND correo IS NOT NULL)
            OR
            (telefono IS NOT NULL AND correo IS NULL))
);