CREATE TABLE public.perfiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username VARCHAR UNIQUE NOT NULL,
    nombre VARCHAR NOT NULL,
    apellido VARCHAR NOT NULL,
    segundo_apellido VARCHAR,
    rol_app VARCHAR NOT NULL CHECK (rol_app IN ('admin', 'voluntario')),
    rol_sistema VARCHAR CHECK (rol_sistema IN ('administracion', 'coordinacion', 'direccion', 'gestion_voluntariado')),
    activo BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK ((rol_app = 'voluntario' AND rol_sistema IS NULL)
            OR
            (rol_app = 'admin' AND rol_sistema IS NOT NULL))
);

CREATE TABLE public.centros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR UNIQUE NOT NULL,
    img VARCHAR,
    estado VARCHAR NOT NULL CHECK (estado IN ('activo', 'inactivo')),
    responsable_id UUID NOT NULL REFERENCES public.perfiles(id),
    mapa_url VARCHAR,
    descripcion TEXT
);