CREATE TABLE public.perfiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username VARCHAR UNIQUE NOT NULL,
    nombre VARCHAR NOT NULL,
    apellido VARCHAR NOT NULL,
    segundo_apellido VARCHAR,
    rol_app VARCHAR NOT NULL CHECK (rol_app IN ('admin', 'voluntario')),
    rol_sistema VARCHAR CHECK (rol_sistema IN ('administracion', 'coordinacion', 'direccion', 'gestion_voluntariado')),
    activo BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK ((rol_app = 'voluntario' AND rol_sistema IS NULL)
            OR
            (rol_app = 'admin' AND rol_sistema IS NOT NULL))
);

CREATE TABLE public.centros (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR UNIQUE NOT NULL,
    img VARCHAR,
    estado VARCHAR NOT NULL CHECK (estado IN ('activo', 'inactivo')),
    responsable_id UUID REFERENCES public.perfiles(id) ON DELETE SET NULL,
    mapa_url VARCHAR,
    descripcion TEXT
);

CREATE TABLE public.vols (
    id UUID PRIMARY KEY REFERENCES public.perfiles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_nacimiento DATE NOT NULL,
    telefono VARCHAR,
    correo VARCHAR,
    area VARCHAR NOT NULL CHECK (area IN ('educacion', 'comunicacion')),
    rol VARCHAR NOT NULL CHECK (rol IN ('apoyo', 'lider', 'responsable')),
    tipo_voluntario VARCHAR NOT NULL CHECK (tipo_voluntario IN ('nacional', 'internacional')),
    pais_origen VARCHAR NOT NULL,
    area_estudio TEXT,
    activo BOOLEAN NOT NULL,
    horas_semana INT NOT NULL CHECK (horas_semana >= 0 AND horas_semana <= 40),
    faltas INT CHECK (faltas >=0 AND faltas <= 3),
    centro_preferido_id INT REFERENCES public.centros(id) ON DELETE SET NULL,
    comentarios TEXT,

    -- A volunteer must provide either phone number or email
    CHECK (telefono IS NOT NULL
        OR correo IS NOT NULL),
    
    -- Phone numbers can't be blank and must include country code and have valid formatting
    CHECK ((telefono IS NULL)
        OR (NULLIF(TRIM(telefono), '') IS NOT NULL
        AND telefono ~ '^\+[1-9][0-9]{7,14}$')),

    -- Emails must have proper formatting and can't be blank
    CHECK (correo IS NULL
        OR (NULLIF(TRIM(correo), '') IS NOT NULL
        AND correo ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'))
);

-- Enforce unique emails, make case insensitive
CREATE UNIQUE INDEX vols_correo_unique_ci
ON public.vols (LOWER(correo));